"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, CalendarDays, Check, ChevronRight, CircleHelp, Clock3, ExternalLink, Eye, LocateFixed, MapPin, MessageSquarePlus, Mic, Navigation, ParkingCircle, Plus, Search, ShieldCheck, Sparkles, Toilet, Trash2, UserRound, Volume2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { RealMap, type ToiletPlace } from "@/components/real-map";
import { assessToilet } from "@/lib/source-engine";

type Lang="nl"|"en"|"de"|"fr"; type View="home"|"places"|"day"|"help"; type Point={lat:number;lon:number};
type Correction={wheelchair:string;fee:string;changingTable:string;access:string;openingHours:string;communityNote:string;verifiedAt:string};
type Reminder={id:string;title:string;at:string;done:boolean};
const words={
 nl:{hello:"Goedemiddag, Luc",sub:"Waarmee kan ik je helpen?",toilet:"Toilet vinden",toiletSub:"Echte locaties bij jou in de buurt",day:"Mijn dag",daySub:"Planning en herinneringen",help:"Hulp onderweg",helpSub:"Snel iemand bereiken",say:"Zeg bijvoorbeeld",example:"Vind een toegankelijk toilet",listening:"Ik luister…",nearby:"Toiletten in de buurt",nearSub:"Eigen en open data, daarna slim door naar Maps",route:"Route naar toilet",back:"Terug",today:"Vandaag",medication:"Medicatieherinnering",call:"Bel mijn contactpersoon",share:"Deel mijn locatie",emergency:"Noodnummer 112",privacy:"Jouw locatie wordt alleen gebruikt om in de buurt te zoeken.",add:"Locatie toevoegen",filter:"Alleen rolstoeltoegankelijk",locate:"Gebruik mijn locatie",loading:"Toiletten zoeken…",none:"Geen passend toilet in de openbare kaartdata gevonden. Controleer Google Maps of vergroot de afstand.",locationDenied:"Geef locatietoegang om toiletten in jouw buurt te vinden.",free:"Gratis",paid:"Betaald",unknown:"Onbekend",open:"Openingstijden",wheelchair:"Rolstoel",changing:"Verschoontafel",source:"Bron",details:"Details",notify:"Melding inschakelen",notificationOn:"Melding staat klaar zolang deze testapp geopend is.",saved:"Op dit apparaat bewaard",name:"Naam van de locatie",save:"Opslaan",cancel:"Annuleren",added:"Eigen locatie",nav:["Start","Kaart","Dag","Hulp"],helpIntro:"Kies wat je nu nodig hebt. Grote knoppen, zonder tussenstappen.",danger:"Alleen bij direct gevaar"},
 en:{hello:"Good afternoon, Luc",sub:"How can I help?",toilet:"Find a toilet",toiletSub:"Real places near you",day:"My day",daySub:"Plans and reminders",help:"Help on the go",helpSub:"Reach someone quickly",say:"Try saying",example:"Find an accessible toilet",listening:"Listening…",nearby:"Nearby toilets",nearSub:"Own and open data, then smart Maps handoff",route:"Route to toilet",back:"Back",today:"Today",medication:"Medication reminder",call:"Call my contact",share:"Share my location",emergency:"Emergency 112",privacy:"Your location is only used to search nearby.",add:"Add a place",filter:"Wheelchair accessible only",locate:"Use my location",loading:"Finding toilets…",none:"No suitable toilet was found in public map data. Check Google Maps or increase the distance.",locationDenied:"Allow location access to find nearby toilets.",free:"Free",paid:"Paid",unknown:"Unknown",open:"Opening hours",wheelchair:"Wheelchair",changing:"Changing table",source:"Source",details:"Details",notify:"Enable notification",notificationOn:"The reminder is ready while this test app remains open.",saved:"Saved on this device",name:"Place name",save:"Save",cancel:"Cancel",added:"My place",nav:["Home","Map","Day","Help"],helpIntro:"Choose what you need. Large buttons, no extra steps.",danger:"Only in immediate danger"},
 de:{hello:"Guten Tag, Luc",sub:"Wobei kann ich helfen?",toilet:"Toilette finden",toiletSub:"Echte Orte in deiner Nähe",day:"Mein Tag",daySub:"Planung und Erinnerungen",help:"Hilfe unterwegs",helpSub:"Schnell jemanden erreichen",say:"Sag zum Beispiel",example:"Finde eine barrierefreie Toilette",listening:"Ich höre zu…",nearby:"Toiletten in der Nähe",nearSub:"Eigene und offene Daten, danach Maps",route:"Route zur Toilette",back:"Zurück",today:"Heute",medication:"Medikamentenerinnerung",call:"Kontaktperson anrufen",share:"Standort teilen",emergency:"Notruf 112",privacy:"Dein Standort wird nur für die Suche in der Nähe verwendet.",add:"Ort hinzufügen",filter:"Nur rollstuhlgerecht",locate:"Meinen Standort verwenden",loading:"Toiletten werden gesucht…",none:"Keine passende Toilette in öffentlichen Kartendaten gefunden. Prüfe Google Maps oder vergrößere den Umkreis.",locationDenied:"Erlaube den Standortzugriff, um Toiletten zu finden.",free:"Kostenlos",paid:"Kostenpflichtig",unknown:"Unbekannt",open:"Öffnungszeiten",wheelchair:"Rollstuhl",changing:"Wickeltisch",source:"Quelle",details:"Details",notify:"Benachrichtigung aktivieren",notificationOn:"Die Erinnerung ist aktiv, solange die Test-App geöffnet bleibt.",saved:"Auf diesem Gerät gespeichert",name:"Name des Ortes",save:"Speichern",cancel:"Abbrechen",added:"Eigener Ort",nav:["Start","Karte","Tag","Hilfe"],helpIntro:"Wähle, was du brauchst. Große Tasten, ohne Umwege.",danger:"Nur bei unmittelbarer Gefahr"},
 fr:{hello:"Bonjour Luc",sub:"Comment puis-je vous aider ?",toilet:"Trouver des toilettes",toiletSub:"Des lieux réels près de vous",day:"Ma journée",daySub:"Planning et rappels",help:"Aide en déplacement",helpSub:"Joindre quelqu’un rapidement",say:"Dites par exemple",example:"Trouve des toilettes accessibles",listening:"Je vous écoute…",nearby:"Toilettes à proximité",nearSub:"Données propres et ouvertes, puis Maps",route:"Itinéraire toilettes",back:"Retour",today:"Aujourd’hui",medication:"Rappel de médicament",call:"Appeler mon contact",share:"Partager ma position",emergency:"Urgences 112",privacy:"Votre position sert uniquement à rechercher à proximité.",add:"Ajouter un lieu",filter:"Accessibles en fauteuil uniquement",locate:"Utiliser ma position",loading:"Recherche des toilettes…",none:"Aucune toilette adaptée trouvée dans les données cartographiques publiques. Vérifiez Google Maps ou élargissez la distance.",locationDenied:"Autorisez la localisation pour trouver des toilettes.",free:"Gratuit",paid:"Payant",unknown:"Inconnu",open:"Horaires",wheelchair:"Fauteuil",changing:"Table à langer",source:"Source",details:"Détails",notify:"Activer la notification",notificationOn:"Le rappel est prêt tant que cette application de test reste ouverte.",saved:"Enregistré sur cet appareil",name:"Nom du lieu",save:"Enregistrer",cancel:"Annuler",added:"Mon lieu",nav:["Accueil","Carte","Jour","Aide"],helpIntro:"Choisissez ce dont vous avez besoin. De grands boutons, sans détour.",danger:"Uniquement en cas de danger immédiat"}
} as const;
const detailText={
 nl:{title:"Toiletdossier",distance:"Afstand",cost:"Kosten",yes:"Ja",no:"Nee",coordinates:"Exacte locatie",access:"Toegang",publicAccess:"Openbaar toegankelijk",operator:"Beheerder",updated:"Bron bijgewerkt",wheelchairNote:"Toelichting rolstoel",supervised:"Toezicht",centralKey:"Centrale sleutel",paper:"Toiletpapier",handwashing:"Handwasvoorziening",hotWater:"Warm water",position:"Toilettype",ostomy:"Stomavriendelijk aangeduid",unisex:"Genderneutraal",drinkingWater:"Drinkwater",declaredSource:"Oorspronkelijke bron",unknownInfo:"‘Onbekend’ betekent dat deze eigenschap nog niet in de openbare kaartdata is vastgelegd. Het betekent niet automatisch dat de voorziening ontbreekt.",close:"Sluiten"},
 en:{title:"Toilet record",distance:"Distance",cost:"Cost",yes:"Yes",no:"No",coordinates:"Exact location",access:"Access",publicAccess:"Public access",operator:"Operator",updated:"Source updated",wheelchairNote:"Wheelchair note",supervised:"Supervision",centralKey:"Central key",paper:"Toilet paper",handwashing:"Handwashing",hotWater:"Hot water",position:"Toilet type",ostomy:"Ostomy signposted",unisex:"Gender neutral",drinkingWater:"Drinking water",declaredSource:"Original source",unknownInfo:"‘Unknown’ means this detail has not yet been recorded in the public map data. It does not automatically mean the facility is unavailable.",close:"Close"},
 de:{title:"Toilettendossier",distance:"Entfernung",cost:"Kosten",yes:"Ja",no:"Nein",coordinates:"Genauer Standort",access:"Zugang",publicAccess:"Öffentlich zugänglich",operator:"Betreiber",updated:"Quelle aktualisiert",wheelchairNote:"Rollstuhlhinweis",supervised:"Aufsicht",centralKey:"Zentralschlüssel",paper:"Toilettenpapier",handwashing:"Handwaschmöglichkeit",hotWater:"Warmwasser",position:"Toilettentyp",ostomy:"Stomafreundlich markiert",unisex:"Geschlechtsneutral",drinkingWater:"Trinkwasser",declaredSource:"Ursprüngliche Quelle",unknownInfo:"„Unbekannt“ bedeutet, dass diese Eigenschaft noch nicht in den öffentlichen Kartendaten erfasst ist. Sie fehlt nicht automatisch.",close:"Schließen"},
 fr:{title:"Dossier des toilettes",distance:"Distance",cost:"Coût",yes:"Oui",no:"Non",coordinates:"Emplacement exact",access:"Accès",publicAccess:"Accès public",operator:"Gestionnaire",updated:"Source mise à jour",wheelchairNote:"Note fauteuil roulant",supervised:"Surveillance",centralKey:"Clé centrale",paper:"Papier toilette",handwashing:"Lavage des mains",hotWater:"Eau chaude",position:"Type de toilettes",ostomy:"Signalé pour stomie",unisex:"Non genré",drinkingWater:"Eau potable",declaredSource:"Source d’origine",unknownInfo:"« Inconnu » signifie que cette information n’est pas encore renseignée dans les données cartographiques publiques. Cela ne signifie pas forcément que l’équipement est absent.",close:"Fermer"}
} as const;
const engineText={
 nl:{title:"Slimme broncontrole",coverage:"Datadekking",confidence:"Betrouwbaarheid",known:"velden bekend",next:"Slimme volgende bron",official:"Gemeente of overheid",operator:"Beheerder van de locatie",open_map:"Open kaartbron",commercial:"Bedrijfs- en locatiebron",verified_community:"Recente gecontroleerde ervaring"},
 en:{title:"Smart source check",coverage:"Data coverage",confidence:"Confidence",known:"fields known",next:"Smart next source",official:"Municipality or government",operator:"Location operator",open_map:"Open map source",commercial:"Business and place source",verified_community:"Recent verified experience"},
 de:{title:"Intelligente Quellenprüfung",coverage:"Datenabdeckung",confidence:"Verlässlichkeit",known:"Felder bekannt",next:"Nächste sinnvolle Quelle",official:"Gemeinde oder Behörde",operator:"Betreiber des Ortes",open_map:"Offene Kartenquelle",commercial:"Unternehmens- und Ortsquelle",verified_community:"Aktuelle geprüfte Erfahrung"},
 fr:{title:"Contrôle intelligent des sources",coverage:"Couverture des données",confidence:"Fiabilité",known:"champs renseignés",next:"Prochaine source utile",official:"Commune ou administration",operator:"Gestionnaire du lieu",open_map:"Source cartographique ouverte",commercial:"Source d’entreprise et de lieu",verified_community:"Expérience récente vérifiée"}
} as const;
const testText={
 nl:{demoButton:"Bekijk een volledig ingevuld voorbeeld",demoBadge:"TESTVOORBEELD – geen echte locatie",searchPlaceholder:"Zoek plaats, adres of onderweg",search:"Zoeken",searchNone:"Die plaats kon ik niet vinden.",searchFailed:"Zoeken lukt nu niet. Probeer je GPS-locatie.",searched:"Zoekgebied",currentLocation:"Mijn actuele locatie",improve:"Gegevens aanvullen",improveTitle:"Wat trof je hier aan?",improveIntro:"Vul alleen in wat je zeker weet. De controle blijft in deze test op jouw apparaat bewaard.",choose:"Niet ingevuld",note:"Korte opmerking, bijvoorbeeld: deur zwaar of oprijplaat aanwezig",verified:"Door jou gecontroleerd",savedCorrection:"Dank je. Jouw controle is meteen in het toiletdossier verwerkt.",website:"Website van de locatie",original:"Oorspronkelijke bron",accessible:"Rolstoeltoegankelijk",public:"Openbaar toegankelijk",streetView:"Ingang / laatste meters",googleCheck:"Controleer dit toilet in Google Maps",likelyToilet:"Deze locatie kan een toilet hebben, maar een openbaar aangepast toilet is nog niet bevestigd."},
 en:{demoButton:"View a fully completed example",demoBadge:"TEST EXAMPLE – not a real location",searchPlaceholder:"Search town, address or along your route",search:"Search",searchNone:"I could not find that place.",searchFailed:"Search is unavailable. Try your GPS location.",searched:"Search area",currentLocation:"My current location",improve:"Add information",improveTitle:"What did you find here?",improveIntro:"Only enter what you know. This test stores your check on this device.",choose:"Not entered",note:"Short note, for example: heavy door or ramp available",verified:"Checked by you",savedCorrection:"Thank you. Your check is now included in the toilet record.",website:"Location website",original:"Original source",accessible:"Wheelchair accessible",public:"Publicly accessible",streetView:"View entrance and surroundings",googleCheck:"Check this toilet in Google Maps",likelyToilet:"This place may have a toilet, but a public accessible toilet is not confirmed yet."},
 de:{demoButton:"Vollständig ausgefülltes Beispiel ansehen",demoBadge:"TESTBEISPIEL – kein echter Ort",searchPlaceholder:"Ort, Adresse oder Strecke suchen",search:"Suchen",searchNone:"Diesen Ort konnte ich nicht finden.",searchFailed:"Die Suche ist gerade nicht verfügbar. Nutze deinen GPS-Standort.",searched:"Suchgebiet",currentLocation:"Mein aktueller Standort",improve:"Angaben ergänzen",improveTitle:"Was hast du hier vorgefunden?",improveIntro:"Trage nur ein, was du sicher weißt. Diese Kontrolle bleibt in diesem Test auf deinem Gerät.",choose:"Nicht eingetragen",note:"Kurzer Hinweis, z. B. schwere Tür oder Rampe vorhanden",verified:"Von dir geprüft",savedCorrection:"Danke. Deine Kontrolle wurde sofort in den Toilettendatensatz übernommen.",website:"Website des Ortes",original:"Ursprüngliche Quelle",accessible:"Rollstuhlgerecht",public:"Öffentlich zugänglich",streetView:"Eingang und Umgebung ansehen",googleCheck:"Diese Toilette in Google Maps prüfen",likelyToilet:"Dieser Ort kann eine Toilette haben, aber eine öffentliche barrierefreie Toilette ist noch nicht bestätigt."},
 fr:{demoButton:"Voir un exemple entièrement rempli",demoBadge:"EXEMPLE TEST – lieu fictif",searchPlaceholder:"Rechercher une ville, adresse ou étape",search:"Rechercher",searchNone:"Je n’ai pas trouvé ce lieu.",searchFailed:"La recherche est indisponible. Essayez votre position GPS.",searched:"Zone recherchée",currentLocation:"Ma position actuelle",improve:"Compléter les informations",improveTitle:"Qu’avez-vous constaté ici ?",improveIntro:"Indiquez uniquement ce dont vous êtes sûr. Ce test conserve votre contrôle sur cet appareil.",choose:"Non renseigné",note:"Courte remarque, par exemple : porte lourde ou rampe disponible",verified:"Vérifié par vous",savedCorrection:"Merci. Votre contrôle est maintenant ajouté au dossier des toilettes.",website:"Site du lieu",original:"Source d’origine",accessible:"Accessible en fauteuil",public:"Accessible au public",streetView:"Voir l’entrée et les alentours",googleCheck:"Vérifier ces toilettes dans Google Maps",likelyToilet:"Ce lieu peut avoir des toilettes, mais des toilettes publiques accessibles ne sont pas encore confirmées."}
} as const;
const appText={
 nl:{settings:"Mijn instellingen",profileName:"Mijn naam",phone:"Telefoonnummer contactpersoon",settingsIntro:"Deze gegevens blijven tijdens de test alleen op dit apparaat.",addReminder:"Herinnering toevoegen",reminderTitle:"Waar wil je aan herinnerd worden?",dateTime:"Datum en tijd",noReminders:"Nog geen herinneringen. Voeg er één toe om dit onderdeel te testen.",completed:"Afgerond",planned:"Gepland",delete:"Verwijderen",testNotice:"Test een melding",noticeSent:"Testmelding verzonden",locationBusy:"Je actuele locatie wordt opgehaald…",demoPlan:"Jouw testplanning op dit apparaat"},
 en:{settings:"My settings",profileName:"My name",phone:"Contact telephone number",settingsIntro:"During this test, these details remain on this device.",addReminder:"Add reminder",reminderTitle:"What should I remind you about?",dateTime:"Date and time",noReminders:"No reminders yet. Add one to test this feature.",completed:"Completed",planned:"Planned",delete:"Delete",testNotice:"Test a notification",noticeSent:"Test notification sent",locationBusy:"Getting your current location…",demoPlan:"Your test plan on this device"},
 de:{settings:"Meine Einstellungen",profileName:"Mein Name",phone:"Telefonnummer der Kontaktperson",settingsIntro:"Diese Angaben bleiben während des Tests auf diesem Gerät.",addReminder:"Erinnerung hinzufügen",reminderTitle:"Woran soll ich dich erinnern?",dateTime:"Datum und Uhrzeit",noReminders:"Noch keine Erinnerungen. Füge eine hinzu, um diese Funktion zu testen.",completed:"Erledigt",planned:"Geplant",delete:"Löschen",testNotice:"Benachrichtigung testen",noticeSent:"Testbenachrichtigung gesendet",locationBusy:"Dein aktueller Standort wird ermittelt…",demoPlan:"Dein Testplan auf diesem Gerät"},
 fr:{settings:"Mes paramètres",profileName:"Mon nom",phone:"Téléphone de la personne à contacter",settingsIntro:"Pendant le test, ces informations restent sur cet appareil.",addReminder:"Ajouter un rappel",reminderTitle:"Que faut-il vous rappeler ?",dateTime:"Date et heure",noReminders:"Aucun rappel. Ajoutez-en un pour tester cette fonction.",completed:"Terminé",planned:"Planifié",delete:"Supprimer",testNotice:"Tester une notification",noticeSent:"Notification test envoyée",locationBusy:"Recherche de votre position actuelle…",demoPlan:"Votre planning test sur cet appareil"}
} as const;
const serviceText={
 nl:{busy:"De openbare kaart is tijdelijk druk. Probeer opnieuw of zet Google Maps gericht aan het werk.",cached:"Eerder bewaarde toiletgegevens worden getoond.",google:"Officiële Google Places-data wordt als betaalde uitwijkbron gebruikt.",retry:"Opnieuw proberen",maps:"Zoek in Google Maps",mapsHint:"Vrijweg stopt hier niet: open een gerichte zoekopdracht naar een rolstoeltoegankelijk toilet rond dit punt.",mapsVenue:"Controleer toilet bij deze locatie",strategyTitle:"Slimme bronvolgorde",openFirst:"Eigen/open data eerst",mapsNext:"Maps als zoek- en navigatielaag",apiLast:"API alleen als dat nodig is",googleTask:"Google-opdracht",inApp:"Resultaten in app ophalen",inAppUnavailable:"Google-resultaten in de app vragen een officiële API-instelling. Gebruik nu de gerichte Maps-knop.",inAppLoading:"Officiële Google-resultaten ophalen…"},
 en:{busy:"The public map service is temporarily busy. Try again or let Google Maps search this exact area.",cached:"Previously saved toilet data is being shown.",google:"Official Google Places data is being used as a paid fallback source.",retry:"Try again",maps:"Search in Google Maps",mapsHint:"Vrijweg does not stop here: open a targeted search for a wheelchair accessible toilet around this point.",mapsVenue:"Check toilet at this place",strategyTitle:"Smart source order",openFirst:"Own/open data first",mapsNext:"Maps as search and navigation layer",apiLast:"API only when needed",googleTask:"Google task",inApp:"Load results in app",inAppUnavailable:"Google results inside the app require an official API setting. Use the targeted Maps button for now.",inAppLoading:"Loading official Google results…"},
 de:{busy:"Der öffentliche Kartendienst ist vorübergehend ausgelastet. Versuche es erneut oder lass Google Maps genau hier suchen.",cached:"Zuvor gespeicherte Toilettendaten werden angezeigt.",google:"Offizielle Google-Places-Daten werden als kostenpflichtige Ausweichquelle verwendet.",retry:"Erneut versuchen",maps:"In Google Maps suchen",mapsHint:"Vrijweg stoppt hier nicht: öffne eine gezielte Suche nach einer rollstuhlgerechten Toilette in der Nähe.",mapsVenue:"Toilette an diesem Ort prüfen",strategyTitle:"Intelligente Quellenfolge",openFirst:"Eigene/offene Daten zuerst",mapsNext:"Maps als Such- und Navigationsschicht",apiLast:"API nur wenn nötig",googleTask:"Google-Auftrag",inApp:"Ergebnisse in der App laden",inAppUnavailable:"Google-Ergebnisse in der App benötigen eine offizielle API-Einstellung. Nutze jetzt die gezielte Maps-Taste.",inAppLoading:"Offizielle Google-Ergebnisse werden geladen…"},
 fr:{busy:"Le service cartographique public est temporairement surchargé. Réessayez ou lancez une recherche ciblée dans Google Maps.",cached:"Les données de toilettes enregistrées précédemment sont affichées.",google:"Les données officielles Google Places sont utilisées comme source payante de secours.",retry:"Réessayer",maps:"Chercher dans Google Maps",mapsHint:"Vrijweg ne s’arrête pas ici : ouvrez une recherche ciblée de toilettes accessibles autour de ce point.",mapsVenue:"Vérifier les toilettes ici",strategyTitle:"Ordre intelligent des sources",openFirst:"Données propres/ouvertes d’abord",mapsNext:"Maps pour recherche et navigation",apiLast:"API seulement si nécessaire",googleTask:"Demande Google",inApp:"Charger dans l’app",inAppUnavailable:"Les résultats Google dans l’app nécessitent un réglage API officiel. Utilisez maintenant le bouton Maps ciblé.",inAppLoading:"Chargement des résultats Google officiels…"}
} as const;
const wheelchairText={
 nl:{title:"Elektrische rolstoel-check",intro:"Voor een elektrische rolstoel tellen vooral de laatste meters en de ruimte binnen.",entrance:"Toegankelijke ingang",width:"Deurbreedte",turning:"Draaicirkel",threshold:"Drempelvrij",surface:"Ondergrond laatste meters",last:"Laatste meters visueel controleren",known:"bekend",unknown:"nog controleren"},
 en:{title:"Power wheelchair check",intro:"For a power wheelchair, the final metres and indoor space matter most.",entrance:"Accessible entrance",width:"Door width",turning:"Turning space",threshold:"Step-free access",surface:"Surface on final metres",last:"Visually check final metres",known:"known",unknown:"check next"},
 de:{title:"E-Rollstuhl-Check",intro:"Für einen E-Rollstuhl zählen vor allem die letzten Meter und der Platz innen.",entrance:"Barrierefreier Eingang",width:"Türbreite",turning:"Wendekreis",threshold:"Stufenlos",surface:"Untergrund der letzten Meter",last:"Letzte Meter visuell prüfen",known:"bekannt",unknown:"noch prüfen"},
 fr:{title:"Contrôle fauteuil électrique",intro:"Pour un fauteuil électrique, les derniers mètres et l’espace intérieur sont essentiels.",entrance:"Entrée accessible",width:"Largeur de porte",turning:"Espace de rotation",threshold:"Sans marche",surface:"Sol des derniers mètres",last:"Vérifier visuellement les derniers mètres",known:"connu",unknown:"à vérifier"}
} as const;

function distance(a:Point,b:Point){const R=6371;const dLat=(b.lat-a.lat)*Math.PI/180;const dLon=(b.lon-a.lon)*Math.PI/180;const q=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function isNearbyToiletQuery(value:string){const q=value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[?!.,]/g," ").replace(/\s+/g," ").trim();return /^(zoek |vind |find |search |suche |trouve |trouver )?(een |a |an |une |un |das |die )?(rolstoeltoegankelijk(e)? |toegankelijk(e)? |invaliden |wheelchair accessible |accessible |barrierefrei(e)? |rollstuhlgerecht(e)? )?(openbaar |public |offentliche |publique(s)? )?(toilet(ten)?|invalidentoilet(ten)?|wc|restroom(s)?|toilette(n)?)( hier| dichtbij| in de buurt| nearby| near me| in meiner nahe| ici| a proximite)?$/.test(q)}
function asksForToilet(value:string){return /(toilet|wc|restroom|toilette|invalidentoilet)/i.test(value)}
function intentContext(value:string,lang:Lang){const q=value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g," ");if(/tank|benzine|fuel|station-service|raststatte|service|rest_area|verzorgingsplaats/.test(q))return({nl:"tankstation of verzorgingsplaats",en:"fuel station or service area",de:"Tankstelle oder Raststätte",fr:"station-service ou aire de service"} as const)[lang];if(/restaurant|cafe|fast.?food|eten|diner|lunch/.test(q))return({nl:"restaurant",en:"restaurant",de:"Restaurant",fr:"restaurant"} as const)[lang];if(/winkel|shopping|mall|centrum|centre commercial|einkaufszentrum/.test(q))return({nl:"winkelcentrum",en:"shopping centre",de:"Einkaufszentrum",fr:"centre commercial"} as const)[lang];if(/parkeer|parking|parkplatz/.test(q))return({nl:"parkeerplaats",en:"parking area",de:"Parkplatz",fr:"parking"} as const)[lang];if(/ingang|entrance|eingang|entree|entrée/.test(q))return({nl:"rolstoeltoegankelijke ingang",en:"wheelchair accessible entrance",de:"rollstuhlgerechter Eingang",fr:"entrée accessible en fauteuil"} as const)[lang];return""}

function makeDemo(point:Point,label:string,lang:Lang):ToiletPlace{const copy={nl:{hours:"Dagelijks 07:00–22:00",source:"Vrijweg demonstratiegegevens",operator:"Voorbeeldbeheerder",wheelchair:"Drempelvrije ingang, deurbreedte 95 cm en voldoende draairuimte.",note:"Ruime cabine; steunbeugels links en rechts. Dit is een fictief voorbeeld om de volledige werking te beoordelen.",raw:"Vrijweg testdossier"},en:{hours:"Daily 07:00–22:00",source:"Vrijweg demonstration data",operator:"Example operator",wheelchair:"Step-free entrance, 95 cm door width and sufficient turning space.",note:"Spacious cubicle; support rails on both sides. This is a fictional example for reviewing the complete experience.",raw:"Vrijweg test record"},de:{hours:"Täglich 07:00–22:00",source:"Vrijweg-Demonstrationsdaten",operator:"Beispielbetreiber",wheelchair:"Stufenloser Eingang, 95 cm Türbreite und ausreichend Wendefläche.",note:"Geräumige Kabine; Haltegriffe links und rechts. Dies ist ein fiktives Beispiel zur Prüfung der vollständigen Funktion.",raw:"Vrijweg-Testdossier"},fr:{hours:"Tous les jours 07:00–22:00",source:"Données de démonstration Vrijweg",operator:"Gestionnaire fictif",wheelchair:"Entrée sans marche, porte de 95 cm et espace de rotation suffisant.",note:"Cabine spacieuse ; barres d’appui des deux côtés. Il s’agit d’un exemple fictif pour évaluer le fonctionnement complet.",raw:"Dossier test Vrijweg"}}[lang];return{id:"vrijweg-demo",name:label,lat:point.lat,lon:point.lon,wheelchair:"yes",fee:"no",openingHours:copy.hours,changingTable:"yes",access:"yes",source:copy.source,demo:true,updatedAt:"2026-08-30T12:00:00Z",operator:copy.operator,wheelchairDescription:copy.wheelchair,supervised:"yes",centralKey:"eurokey",paperSupplied:"yes",handwashing:"yes",hotWater:"yes",position:"seated",ostomy:"yes",unisex:"yes",drinkingWater:"yes",communityNote:copy.note,rawSource:copy.raw}}
function inputDateTime(date=new Date(Date.now()+3600000)){const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function googleMapsQuery(point:Point,lang:Lang,context?:ToiletPlace|null,intent="",r=5000){const query=({nl:"openbaar aangepast toilet OR invalidentoilet OR rolstoeltoegankelijk WC geschikt voor elektrische rolstoel -frietwagen -eetkraam -foodtruck -snackbar",en:"public accessible restroom OR wheelchair accessible toilet suitable for power wheelchair -foodtruck -snack bar -kiosk",de:"öffentliche barrierefreie Toilette OR Rollstuhl-WC geeignet für Elektrorollstuhl -Imbisswagen -Foodtruck -Kiosk",fr:"toilettes publiques accessibles OR WC accessible fauteuil électrique -foodtruck -kiosque -snack"} as const)[lang];const near=({nl:"bij",en:"near",de:"bei",fr:"près de"} as const)[lang];const around=({nl:"rond",en:"around",de:"rund um",fr:"autour de"} as const)[lang];const within=({nl:"binnen",en:"within",de:"innerhalb",fr:"dans un rayon de"} as const)[lang];const detected=intentContext(intent,lang);const target=context?.name?`${near} ${context.name}`:detected?`${near} ${detected}`:"";return `${query} ${target} ${around} ${point.lat.toFixed(5)},${point.lon.toFixed(5)} ${within} ${Math.max(1,Math.round(r/1000))} km`.replace(/\s+/g," ").trim()}
function mapsSearchUrl(point:Point,lang:Lang,context?:ToiletPlace|null,intent="",r=5000){return `https://www.google.com/maps/search/?${new URLSearchParams({api:"1",query:googleMapsQuery(point,lang,context,intent,r)}).toString()}`}
function mapsDirectionsUrl(place:ToiletPlace,origin:Point|null){const params=new URLSearchParams({api:"1",destination:place.googlePlaceId?place.name:`${place.lat},${place.lon}`,travelmode:"driving",dir_action:"navigate"});if(origin)params.set("origin",`${origin.lat},${origin.lon}`);if(place.googlePlaceId)params.set("destination_place_id",place.googlePlaceId);return `https://www.google.com/maps/dir/?${params.toString()}`}
function isUnsuitableToiletFallback(tags:Record<string,string>){const text=Object.values(tags).join(" ").toLowerCase();return /(fast_food|food_truck|friet|frites|snack|snackbar|eetkraam|kraam|kiosk|ice_cream|catering|mobile)/.test(text)}
function isConfirmedToilet(tags:Record<string,string>){return tags.amenity==="toilets"||Boolean(tags.toilets&&tags.toilets!=="no")}

export default function Home(){
 const [lang,setLang]=useState<Lang>("nl"),[view,setView]=useState<View>("home"),[listening,setListening]=useState(false),[center,setCenter]=useState<Point|null>(null),[places,setPlaces]=useState<ToiletPlace[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[sourceNotice,setSourceNotice]=useState(""),[accessibleOnly,setAccessibleOnly]=useState(false),[radius,setRadius]=useState(5000),[addOpen,setAddOpen]=useState(false),[detailsOpen,setDetailsOpen]=useState(false),[reportOpen,setReportOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[reminderOpen,setReminderOpen]=useState(false),[newName,setNewName]=useState(""),[custom,setCustom]=useState<ToiletPlace[]>([]),[corrections,setCorrections]=useState<Record<string,Correction>>({}),[searchQuery,setSearchQuery]=useState(""),[searchLabel,setSearchLabel]=useState(""),[reportSaved,setReportSaved]=useState(false),[notice,setNotice]=useState(false),[profileName,setProfileName]=useState("Luc"),[contact,setContact]=useState(""),[reminders,setReminders]=useState<Reminder[]>([]),[reminderTitle,setReminderTitle]=useState(""),[reminderAt,setReminderAt]=useState(inputDateTime()); const t=words[lang]; const dt=detailText[lang]; const tt=testText[lang]; const at=appText[lang]; const st=serviceText[lang]; const wt=wheelchairText[lang];
 const [draft,setDraft]=useState<Omit<Correction,"verifiedAt">>({wheelchair:"",fee:"",changingTable:"",access:"",openingHours:"",communityNote:""});
 const markDone=lang==="nl"?"Markeer als afgerond":lang==="de"?"Als erledigt markieren":lang==="fr"?"Marquer comme terminé":"Mark as completed";
 const detailValue=(value:string)=>value==="yes"?dt.yes:value==="no"?dt.no:value==="unknown"?t.unknown:value==="seated"?(lang==="nl"?"Zittend":lang==="de"?"Sitzend":lang==="fr"?"Assis":"Seated"):value;
 useEffect(()=>{try{setCustom(JSON.parse(localStorage.getItem("vrijweg-places")||"[]"));setCorrections(JSON.parse(localStorage.getItem("vrijweg-corrections")||"{}"));setProfileName(localStorage.getItem("vrijweg-name")||"Luc");setContact(localStorage.getItem("vrijweg-contact")||"");const stored=JSON.parse(localStorage.getItem("vrijweg-reminders")||"[]") as Reminder[];setReminders(stored)}catch{}},[]);
 const findToilets=async(point:Point,r=radius)=>{
  setLoading(true);setError("");setSourceNotice("");
	 const cacheKey=`vrijweg-toilets-v3-${point.lat.toFixed(2)}-${point.lon.toFixed(2)}-${r}`;
  try{const cached=JSON.parse(localStorage.getItem(cacheKey)||"null") as {savedAt:number;items:ToiletPlace[]}|null;if(cached&&Date.now()-cached.savedAt<7*24*60*60*1000){setPlaces(cached.items);setSelectedId(cached.items[0]?.id||null);setSourceNotice(st.cached);setLoading(false);return}}catch{}
	  const venueRadius=Math.min(r,750);
	  const query=`[out:json][timeout:12];(nwr["amenity"="toilets"](around:${r},${point.lat},${point.lon});nwr["toilets"]["toilets"!="no"](around:${r},${point.lat},${point.lon});nwr["toilets:wheelchair"~"^(yes|designated)$"](around:${r},${point.lat},${point.lon});nwr["amenity"="fuel"](around:${venueRadius},${point.lat},${point.lon});nwr["highway"~"^(services|rest_area)$"](around:${venueRadius},${point.lat},${point.lon}););out center tags qt;`;
  const endpoints=["https://overpass.private.coffee/api/interpreter","https://maps.mail.ru/osm/tools/overpass/api/interpreter","https://overpass-api.de/api/interpreter"];
  let openMapAnswered=false;
  for(const endpoint of endpoints){
   try{
    const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({data:query}),signal:AbortSignal.timeout(8000)});
    if(!response.ok)continue;
    openMapAnswered=true;
    const data=await response.json() as {elements?:Array<{id:number;lat?:number;lon?:number;center?:{lat:number;lon:number};tags?:Record<string,string>}>};
	    const items=(data.elements||[]).map(element=>{const tags=element.tags||{};const pointData=element.center||{lat:element.lat,lon:element.lon};if(pointData.lat==null||pointData.lon==null)return null;const confirmed=isConfirmedToilet(tags);if(!confirmed&&isUnsuitableToiletFallback(tags))return null;const kind=tags.amenity||tags.highway||"venue";const fallback=kind==="fuel"?(lang==="fr"?"Station-service":lang==="de"?"Tankstelle":lang==="en"?"Fuel station":"Tankstation"):kind==="services"||kind==="rest_area"?(lang==="fr"?"Aire de service":lang==="de"?"Raststätte":lang==="en"?"Service area":"Verzorgingsplaats"):"Openbaar toilet";return{id:`osm-${element.id}`,name:tags.name||tags.operator||fallback,lat:pointData.lat,lon:pointData.lon,wheelchair:confirmed?(tags["toilets:wheelchair"]||tags.wheelchair||"unknown"):(tags["toilets:wheelchair"]||"unknown"),fee:confirmed?(tags.fee||"unknown"):"unknown",openingHours:tags.opening_hours||null,changingTable:tags.changing_table||"unknown",access:tags.access||"yes",source:confirmed?"OpenStreetMap":"OpenStreetMap – nabije locatie",inferred:!confirmed,updatedAt:null,operator:tags.operator||null,website:tags.website||tags["contact:website"]||null,wheelchairDescription:tags["wheelchair:description"]||null,supervised:tags.supervised||null,centralKey:tags.centralkey||null,paperSupplied:tags["toilets:paper_supplied"]||null,handwashing:tags["toilets:handwashing"]||null,hotWater:tags.hot_water||null,position:tags["toilets:position"]||null,ostomy:tags["toilets:ostomy"]||null,unisex:tags.unisex||null,drinkingWater:tags.drinking_water||null,rawSource:tags.source||null,communityNote:confirmed?null:tt.likelyToilet} as ToiletPlace}).filter((item):item is ToiletPlace=>item!==null).sort((a,b)=>(Number(a.inferred)-Number(b.inferred))||distance(point,a)-distance(point,b));
    if(items.length===0)continue;
    setPlaces(items);setSelectedId(items[0]?.id||null);localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),items}));setLoading(false);return;
   }catch{}
  }
  setPlaces([]);setSelectedId(null);setError(openMapAnswered?"":st.busy);setLoading(false);
 };
 const locate=()=>{if(!navigator.geolocation){setError(t.locationDenied);return}setLoading(true);navigator.geolocation.getCurrentPosition(p=>{const point={lat:p.coords.latitude,lon:p.coords.longitude};setCenter(point);findToilets(point)},()=>{setLoading(false);setError(t.locationDenied)},{enableHighAccuracy:true,timeout:12000,maximumAge:120000})};
 useEffect(()=>{if(view==="places"&&!center&&!loading)locate()},[view]);
 const allPlaces=useMemo(()=>[...custom,...places].map(place=>{const correction=corrections[place.id];return correction?{...place,...Object.fromEntries(Object.entries(correction).filter(([key,value])=>key==="verifiedAt"||value!=="")),baseSource:place.source,source:`${place.source} + ${tt.verified}`,updatedAt:correction.verifiedAt}:place}).filter(p=>!accessibleOnly||p.wheelchair==="yes"||p.wheelchair==="designated"||p.custom).sort((a,b)=>center?(Number(a.inferred)-Number(b.inferred))||distance(center,a)-distance(center,b):Number(a.inferred)-Number(b.inferred)),[custom,places,corrections,accessibleOnly,center,tt.verified]);
 const selected=allPlaces.find(p=>p.id===selectedId)||allPlaces[0]||null;
 const candidatePlaces=allPlaces.slice(0,4);
 const assessment=useMemo(()=>selected?assessToilet(selected):null,[selected]); const et=engineText[lang];
 const electricChecks=selected?[{label:wt.entrance,known:selected.wheelchair==="yes"||selected.wheelchair==="designated"||Boolean(selected.wheelchairDescription)},{label:wt.width,known:Boolean(selected.wheelchairDescription?.match(/\d+\s*cm|width|breedte|largeur|breite/i))},{label:wt.turning,known:Boolean(selected.wheelchairDescription?.match(/draai|turn|rotation|wend/i))},{label:wt.threshold,known:Boolean(selected.wheelchairDescription?.match(/drempel|step-free|zonder trede|sans marche|stufenlos/i))},{label:wt.surface,known:false},{label:wt.last,known:Boolean(selected.lat&&selected.lon)}]:[];
 const sortedReminders=useMemo(()=>[...reminders].sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime()),[reminders]);
 const nextReminder=sortedReminders.find(item=>!item.done)||sortedReminders[0]||null;
 const speak=()=>{setListening(true);const W=window as typeof window&{webkitSpeechRecognition?:new()=>{lang:string;start:()=>void;onresult:(e:{results:ArrayLike<{0:{transcript:string}}>} )=>void;onerror:()=>void;onend:()=>void}};const Recognition=W.webkitSpeechRecognition;if(!Recognition){setTimeout(()=>{setListening(false);setView("places")},900);return}const recognition=new Recognition();recognition.lang=lang==="nl"?"nl-NL":lang==="de"?"de-DE":lang==="fr"?"fr-FR":"en-US";recognition.onresult=e=>{const q=e.results[0][0].transcript.toLowerCase();if(/dag|plan|medic|termin|jour/.test(q))setView("day");else if(/help|hulp|hilfe|aide|nood|urgence/.test(q))setView("help");else setView("places")};recognition.onerror=()=>setListening(false);recognition.onend=()=>setListening(false);recognition.start()};
 const route=()=>{if(!selected)return;if(selected.demo){setDetailsOpen(true);return}window.location.assign(mapsDirectionsUrl(selected,center))};
 const googleCheck=()=>{if(!selected||selected.demo)return;if(selected.googlePlaceId){const params=new URLSearchParams({api:"1",query:selected.name,query_place_id:selected.googlePlaceId});window.location.assign(`https://www.google.com/maps/search/?${params.toString()}`);return}window.location.assign(mapsSearchUrl({lat:selected.lat,lon:selected.lon},lang,selected.inferred?selected:null,searchQuery,radius))};
 const streetView=()=>{if(!selected||selected.demo)return;const params=new URLSearchParams({api:"1",map_action:"pano",viewpoint:`${selected.lat},${selected.lon}`});window.location.assign(`https://www.google.com/maps/@?${params.toString()}`)};
 const mapsFallback=()=>{const point=center||selected;if(!point)return;window.location.assign(mapsSearchUrl(point,lang,selected?.inferred?selected:null,searchQuery,radius))};
 const openDemo=()=>{const point=center||{lat:51.747,lon:5.26};const demo=makeDemo(point,tt.demoBadge,lang);setError("");setLoading(false);setPlaces(current=>[demo,...current.filter(place=>place.id!==demo.id)]);setSelectedId(demo.id);setDetailsOpen(true)};
 const closeDetails=()=>{setDetailsOpen(false);if(selected?.demo){setPlaces(current=>current.filter(place=>!place.demo));setSelectedId(null)}};
 const searchArea=async()=>{const entered=searchQuery.trim();if(!entered)return;setLoading(true);setError("");setSourceNotice("");const intent=intentContext(entered,lang);if(isNearbyToiletQuery(entered)||(intent&&asksForToilet(entered))){try{const point=await getPosition();setCenter(point);setSearchLabel(intent?`${intent} · ${tt.currentLocation}`:tt.currentLocation);await findToilets(point)}catch{setError(t.locationDenied);setLoading(false)}return}const q=entered.replace(/^(zoek|vind)\s+(een\s+)?(rolstoeltoegankelijke?\s+toilet|invalidentoilet|toilet)\s+(in|bij|nabij)\s+/i,"").trim()||entered;try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&accept-language=${lang}&q=${encodeURIComponent(q)}`,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error();const results=await response.json() as Array<{lat:string;lon:string;display_name:string}>;if(!results[0]){setError(tt.searchNone);setLoading(false);return}const point={lat:Number(results[0].lat),lon:Number(results[0].lon)};setCenter(point);setSearchLabel(results[0].display_name);await findToilets(point)}catch{setError(tt.searchFailed);setLoading(false)}};
 const openReport=()=>{if(!selected)return;const existing=corrections[selected.id];setDraft({wheelchair:existing?.wheelchair||"",fee:existing?.fee||"",changingTable:existing?.changingTable||"",access:existing?.access||"",openingHours:existing?.openingHours||"",communityNote:existing?.communityNote||""});setReportSaved(false);setReportOpen(true)};
 const saveReport=()=>{if(!selected)return;const correction:Correction={...draft,verifiedAt:new Date().toISOString()};const next={...corrections,[selected.id]:correction};setCorrections(next);localStorage.setItem("vrijweg-corrections",JSON.stringify(next));setReportSaved(true);setTimeout(()=>setReportOpen(false),900)};
 const savePlace=()=>{if(!center||!newName.trim())return;const p:ToiletPlace={id:`local-${Date.now()}`,name:newName.trim(),lat:center.lat,lon:center.lon,wheelchair:"yes",fee:"unknown",openingHours:null,changingTable:"unknown",access:"yes",source:t.saved,custom:true};const next=[p,...custom];setCustom(next);localStorage.setItem("vrijweg-places",JSON.stringify(next));setSelectedId(p.id);setNewName("");setAddOpen(false)};
 const storeReminders=(next:Reminder[])=>{setReminders(next);localStorage.setItem("vrijweg-reminders",JSON.stringify(next))};
 const saveReminder=()=>{if(!reminderTitle.trim()||!reminderAt)return;storeReminders([...reminders,{id:`reminder-${Date.now()}`,title:reminderTitle.trim(),at:new Date(reminderAt).toISOString(),done:false}]);setReminderTitle("");setReminderAt(inputDateTime());setReminderOpen(false)};
 const toggleReminder=(id:string)=>storeReminders(reminders.map(item=>item.id===id?{...item,done:!item.done}:item));
 const deleteReminder=(id:string)=>storeReminders(reminders.filter(item=>item.id!==id));
 const saveSettings=()=>{const safe=contact.replace(/[^+\d\s()-]/g,"");setContact(safe);localStorage.setItem("vrijweg-name",profileName.trim()||"Luc");localStorage.setItem("vrijweg-contact",safe);setSettingsOpen(false)};
 const enableNotice=async()=>{if(!("Notification" in window)){setNotice(true);return}const permission=await Notification.requestPermission();if(permission==="granted"){setNotice(true);new Notification(nextReminder?.title||t.medication,{body:at.noticeSent})}};
 const getPosition=()=>new Promise<Point>((resolve,reject)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:30000}):reject());
 const share=async()=>{let point=center;try{if(!point){setError(at.locationBusy);point=await getPosition();setCenter(point);setError("")}const text=`${t.share}: https://www.google.com/maps?q=${point.lat},${point.lon}`;if(navigator.share)await navigator.share({title:"Vrijweg",text});else await navigator.clipboard.writeText(text)}catch{setError(t.locationDenied);setView("places")}};
 const callContact=()=>{const safe=contact.replace(/[^+\d]/g,"");if(!safe){setSettingsOpen(true);return}window.location.href=`tel:${safe}`};
 const title=view==="places"?t.toilet:view==="day"?t.day:view==="help"?t.help:t.hello.replace("Luc",profileName||"Luc");
 return <main className="app-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><section className="phone-stage">
  <header className="topbar"><button className="brand" onClick={()=>setView("home")}><span className="brand-mark"><Navigation size={21}/></span><span>vrijweg</span></button><div className="top-actions"><select value={lang} onChange={e=>setLang(e.target.value as Lang)} aria-label="Taal"><option value="nl">NL</option><option value="en">EN</option><option value="de">DE</option><option value="fr">FR</option></select><button className="round-icon" onClick={()=>setView("day")} aria-label={t.day}><Bell size={20}/>{reminders.some(item=>!item.done)&&<span className="notice"/>}</button><button className="avatar" onClick={()=>setSettingsOpen(true)} aria-label={at.settings}><UserRound size={19}/></button></div></header>
  <div className="content">{view!=="home"&&<button className="back" onClick={()=>setView("home")}><X size={17}/>{t.back}</button>}<div className="greeting"><p className="eyebrow">{view==="home"?t.today:"VRIJWEG"}</p><h1>{title}</h1>{view==="home"&&<p>{t.sub}</p>}</div>
  {view==="places"&&<button className="demo-launch" onClick={openDemo}><Sparkles size={18}/><span><b>{tt.demoButton}</b><small>{tt.demoBadge}</small></span><ChevronRight size={18}/></button>}
  {view==="home"&&<><div className="action-grid"><button className="action-card coral" onClick={()=>setView("places")}><span className="action-icon"><Toilet size={28}/></span><span><b>{t.toilet}</b><small>{t.toiletSub}</small></span><ChevronRight/></button><button className="action-card blue" onClick={()=>setView("day")}><span className="action-icon"><CalendarDays size={27}/></span><span><b>{t.day}</b><small>{t.daySub}</small></span><ChevronRight/></button><button className="action-card sand" onClick={()=>setView("help")}><span className="action-icon"><CircleHelp size={28}/></span><span><b>{t.help}</b><small>{t.helpSub}</small></span><ChevronRight/></button></div><section className={`voice-card ${listening?"is-listening":""}`}><button className="mic-button" onClick={speak} aria-label={t.example}><Mic size={31}/></button><div><span>{listening?t.listening:t.say}</span><strong>“{t.example}”</strong></div><Volume2 className="speaker"/></section><div className="reassurance"><ShieldCheck size={18}/><span>{t.privacy}</span></div></>}
  {view==="places"&&<div className="places-layout">
   <form className="place-search" onSubmit={e=>{e.preventDefault();searchArea()}}><Input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder={tt.searchPlaceholder} aria-label={tt.searchPlaceholder}/><Button type="submit" aria-label={tt.search}><Search size={19}/><span>{tt.search}</span></Button></form>
   {searchLabel&&<p className="search-label"><MapPin size={14}/>{tt.searched}: {searchLabel}</p>}
   <div className="live-map-wrap"><RealMap center={center} places={allPlaces} selectedId={selected?.id||null} onSelect={setSelectedId}/><div className="map-controls live"><button className={`filter-pill ${accessibleOnly?"active":""}`} onClick={()=>setAccessibleOnly(!accessibleOnly)}><Sparkles size={15}/>{t.filter}</button><button className="locate" onClick={()=>{setSearchLabel("");locate()}} title={t.locate}><LocateFixed size={19}/></button></div>{selected&&!selected.demo&&<div className="map-route-card"><div><span>{center?`${distance(center,selected).toFixed(1)} km`:""}</span><b>{selected.name}</b></div><div className="map-route-actions"><button className="route-main" onClick={selected.inferred?googleCheck:route} aria-label={`${selected.inferred?st.mapsVenue:t.route}: ${selected.name}`}><Navigation size={16}/>{selected.inferred?st.mapsVenue:t.route}</button><button className="route-secondary" onClick={streetView} aria-label={`${tt.streetView}: ${selected.name}`}><Eye size={16}/>{tt.streetView}</button></div></div>}</div>
   <div className="radius-row"><span>{radius/1000} km</span><input type="range" min="1000" max="10000" step="1000" value={radius} onChange={e=>setRadius(Number(e.target.value))}/><button onClick={()=>center&&findToilets(center,radius)}>{tt.search}</button></div>
   {loading&&<div className="status-card"><span className="loader"/>{t.loading}</div>}
   {sourceNotice&&<div className="status-card cached"><ShieldCheck size={18}/>{sourceNotice}</div>}
   {error&&<div className="status-card error"><span>{error}</span><div className="status-actions"><Button size="sm" onClick={()=>center?findToilets(center,radius):locate()}>{st.retry}</Button>{center&&<Button size="sm" variant="outline" onClick={mapsFallback}><MapPin size={16}/>{st.maps}</Button>}</div></div>}
   {!loading&&!error&&!selected&&<div className="status-card empty-search"><div><b>{t.none}</b><small>{center?st.mapsHint:t.privacy}</small></div>{center&&<Button size="sm" onClick={mapsFallback}><MapPin size={16}/>{st.maps}</Button>}</div>}
   {selected&&<section className="results"><div className="result-heading"><div><h2>{t.nearby}</h2><p>{candidatePlaces.length} opties dichtbij</p></div><button className="add-place" onClick={()=>setAddOpen(true)}><Plus size={18}/><span>{t.add}</span></button></div>{candidatePlaces.length>1&&<div className="candidate-list">{candidatePlaces.map(place=><button className={place.id===selected.id?"active":""} onClick={()=>setSelectedId(place.id)} key={place.id}><span>{center?`${distance(center,place).toFixed(1)} km`:""}</span><b>{place.name}</b><small>{place.inferred?st.mapsVenue:place.wheelchair==="yes"||place.wheelchair==="designated"?t.wheelchair:t.unknown}</small></button>)}</div>}<article className="place-card"><div className="place-top"><div><span className="distance"><MapPin size={14}/>{center?`${distance(center,selected).toFixed(1)} km`:""}</span><h3>{selected.name}</h3></div>{selected.custom&&<span className="rating">{t.added}</span>}</div>{selected.inferred&&<p className="likely-toilet"><CircleHelp size={17}/>{tt.likelyToilet}</p>}<div className="place-actions"><Button className="route-button" onClick={selected.inferred?googleCheck:route}><Navigation size={17}/>{selected.inferred?st.mapsVenue:t.route}</Button><Button variant="outline" onClick={()=>setDetailsOpen(true)}>{t.details}</Button></div><button className="improve-button" onClick={openReport}><MessageSquarePlus size={16}/>{tt.improve}</button></article></section>}
  </div>}
  {view==="day"&&<div className="day-layout">{nextReminder?<section className="next-card"><span className="section-label">{at.demoPlan}</span><div className="time-row"><span className="big-time">{new Date(nextReminder.at).toLocaleTimeString(lang,{hour:"2-digit",minute:"2-digit"})}</span><span className="in-time">{new Date(nextReminder.at).toLocaleDateString(lang,{day:"numeric",month:"short"})}</span></div><h2>{nextReminder.title}</h2><p>{nextReminder.done?at.completed:at.planned} · {t.saved}</p><button className={`done-button ${nextReminder.done?"done":""}`} onClick={()=>toggleReminder(nextReminder.id)}><span>{nextReminder.done&&<Check size={18}/>}</span>{nextReminder.done?at.completed:markDone}</button></section>:<section className="empty-plan"><CalendarDays/><p>{at.noReminders}</p></section>}<div className="day-actions"><Button onClick={()=>setReminderOpen(true)}><Plus/>{at.addReminder}</Button><Button variant="outline" onClick={enableNotice}><Bell/>{notice?at.noticeSent:at.testNotice}</Button></div><section className="timeline"><h2>{t.today}</h2>{sortedReminders.length===0?<p className="timeline-empty">{at.noReminders}</p>:sortedReminders.map(item=><div className={`timeline-item ${item.done?"passed":"current"}`} key={item.id}><span>{new Date(item.at).toLocaleTimeString(lang,{hour:"2-digit",minute:"2-digit"})}</span><i/><div><b>{item.title}</b><small>{new Date(item.at).toLocaleDateString(lang,{weekday:"short",day:"numeric",month:"short"})} · {item.done?at.completed:at.planned}</small></div><button className="delete-reminder" onClick={()=>deleteReminder(item.id)} aria-label={at.delete}><Trash2 size={16}/></button></div>)}</section></div>}
  {view==="help"&&<div className="help-layout"><p className="help-intro">{t.helpIntro}</p><button className="help-action primary-help" onClick={callContact}><span><UserRound/></span><div><b>{t.call}</b><small>{t.saved}</small></div><ChevronRight/></button><button className="help-action" onClick={share}><span><MapPin/></span><div><b>{t.share}</b><small>{t.privacy}</small></div><ChevronRight/></button><a className="help-action emergency" href="tel:112"><span><Bell/></span><div><b>{t.emergency}</b><small>{t.danger}</small></div><ChevronRight/></a><div className="profile-note"><ShieldCheck/><div><b>Vrijweg</b><p>{t.privacy}</p></div></div></div>}
  </div><nav className="bottom-nav"><button className={view==="home"?"active":""} onClick={()=>setView("home")}><Sparkles/><span>{t.nav[0]}</span></button><button className={view==="places"?"active":""} onClick={()=>setView("places")}><MapPin/><span>{t.nav[1]}</span></button><button className="central-mic" onClick={speak} aria-label={t.example}><Mic/></button><button className={view==="day"?"active":""} onClick={()=>setView("day")}><Clock3/><span>{t.nav[2]}</span></button><button className={view==="help"?"active":""} onClick={()=>setView("help")}><ParkingCircle/><span>{t.nav[3]}</span></button></nav>
 </section><aside className="concept-note"><span>WERKENDE TESTVERSIE</span><strong>Vrijweg</strong><p>GPS · echte kaart · routes · spraak</p></aside>
 <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>{t.add}</DialogTitle><DialogDescription>{t.saved}. De huidige GPS-positie wordt gebruikt.</DialogDescription></DialogHeader><Input value={newName} onChange={e=>setNewName(e.target.value)} placeholder={t.name}/><DialogFooter><Button variant="outline" onClick={()=>setAddOpen(false)}>{t.cancel}</Button><Button onClick={savePlace}>{t.save}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={detailsOpen} onOpenChange={open=>open?setDetailsOpen(true):closeDetails()}><DialogContent className="toilet-details"><DialogHeader><DialogTitle>{dt.title}</DialogTitle><DialogDescription>{selected?.name}</DialogDescription></DialogHeader>{selected&&<div className="detail-list">
  <div><span>{dt.distance}</span><b>{center?`${distance(center,selected).toFixed(1)} km`:t.unknown}</b></div><div><span>{t.wheelchair}</span><b>{selected.wheelchair==="designated"?dt.yes:detailValue(selected.wheelchair)}</b></div>{selected.wheelchairDescription&&<div><span>{dt.wheelchairNote}</span><b>{selected.wheelchairDescription}</b></div>}<div><span>{t.changing}</span><b>{detailValue(selected.changingTable)}</b></div><div><span>{dt.cost}</span><b>{selected.fee==="no"?t.free:selected.fee==="yes"?t.paid:t.unknown}</b></div><div><span>{t.open}</span><b>{selected.openingHours||t.unknown}</b></div><div><span>{dt.access}</span><b>{selected.access==="yes"?dt.publicAccess:detailValue(selected.access||"unknown")}</b></div>{selected.operator&&<div><span>{dt.operator}</span><b>{selected.operator}</b></div>}{selected.supervised&&<div><span>{dt.supervised}</span><b>{detailValue(selected.supervised)}</b></div>}{selected.centralKey&&<div><span>{dt.centralKey}</span><b>{detailValue(selected.centralKey)}</b></div>}{selected.paperSupplied&&<div><span>{dt.paper}</span><b>{detailValue(selected.paperSupplied)}</b></div>}{selected.handwashing&&<div><span>{dt.handwashing}</span><b>{detailValue(selected.handwashing)}</b></div>}{selected.hotWater&&<div><span>{dt.hotWater}</span><b>{detailValue(selected.hotWater)}</b></div>}{selected.position&&<div><span>{dt.position}</span><b>{detailValue(selected.position)}</b></div>}{selected.ostomy&&<div><span>{dt.ostomy}</span><b>{detailValue(selected.ostomy)}</b></div>}{selected.unisex&&<div><span>{dt.unisex}</span><b>{detailValue(selected.unisex)}</b></div>}{selected.drinkingWater&&<div><span>{dt.drinkingWater}</span><b>{detailValue(selected.drinkingWater)}</b></div>}{selected.communityNote&&<div><span>{tt.verified}</span><b>{selected.communityNote}</b></div>}<div><span>{t.source}</span><b>{selected.source}</b></div>{selected.baseSource&&<div><span>{tt.original}</span><b>{selected.baseSource}</b></div>}{selected.rawSource&&<div><span>{dt.declaredSource}</span><b>{selected.rawSource}</b></div>}{selected.updatedAt&&<div><span>{dt.updated}</span><b>{new Date(selected.updatedAt).toLocaleDateString(lang)}</b></div>}{selected.website&&<div><span>{tt.website}</span><b><a href={selected.website} target="_blank" rel="noreferrer">{tt.website} <ExternalLink size={12}/></a></b></div>}
  </div>}{assessment&&<section className="engine-card"><div className="engine-heading"><ShieldCheck size={19}/><b>{et.title}</b></div><div className="engine-metric"><span>{et.coverage}</span><b>{assessment.completeness}%</b><i><em style={{width:`${assessment.completeness}%`}}/></i><small>{assessment.known}/{assessment.total} {et.known}</small></div><div className="engine-metric"><span>{et.confidence}</span><b>{assessment.confidence}%</b><i><em style={{width:`${assessment.confidence}%`}}/></i></div>{assessment.nextSources.length>0&&<div className="next-sources"><strong>{et.next}</strong>{assessment.nextSources.map(source=><span key={source}>{et[source]}</span>)}</div>}</section>}{selected&&<section className="wheelchair-check"><div><ShieldCheck size={18}/><b>{wt.title}</b></div><p>{wt.intro}</p>{electricChecks.map(item=><span className={item.known?"known":"unknown"} key={item.label}>{item.label}: {item.known?wt.known:wt.unknown}</span>)}</section>}<p className="unknown-note"><CircleHelp size={18}/>{dt.unknownInfo}</p><div className="detail-actions"><Button variant="outline" onClick={openReport}><MessageSquarePlus size={16}/>{tt.improve}</Button>{selected&&!selected.demo&&<Button variant="outline" onClick={streetView}><Eye size={17}/>{tt.streetView}</Button>}{selected&&!selected.demo&&<Button className="google-check" variant="outline" onClick={googleCheck}><MapPin size={17}/>{tt.googleCheck}</Button>}</div><DialogFooter><Button variant="outline" onClick={closeDetails}>{dt.close}</Button>{selected&&!selected.demo&&<Button className="route-button" onClick={selected.inferred?googleCheck:route}><Navigation size={17}/>{selected.inferred?st.mapsVenue:t.route}</Button>}</DialogFooter></DialogContent></Dialog>
 <Dialog open={reportOpen} onOpenChange={setReportOpen}><DialogContent className="report-dialog"><DialogHeader><DialogTitle>{tt.improveTitle}</DialogTitle><DialogDescription>{selected?.name}<br/>{tt.improveIntro}</DialogDescription></DialogHeader>{reportSaved?<div className="report-success"><Check/>{tt.savedCorrection}</div>:<div className="report-grid"><label><span>{tt.accessible}</span><select value={draft.wheelchair} onChange={e=>setDraft({...draft,wheelchair:e.target.value})}><option value="">{tt.choose}</option><option value="yes">{dt.yes}</option><option value="no">{dt.no}</option></select></label><label><span>{tt.public}</span><select value={draft.access} onChange={e=>setDraft({...draft,access:e.target.value})}><option value="">{tt.choose}</option><option value="yes">{dt.yes}</option><option value="private">{dt.no}</option></select></label><label><span>{dt.cost}</span><select value={draft.fee} onChange={e=>setDraft({...draft,fee:e.target.value})}><option value="">{tt.choose}</option><option value="no">{t.free}</option><option value="yes">{t.paid}</option></select></label><label><span>{t.changing}</span><select value={draft.changingTable} onChange={e=>setDraft({...draft,changingTable:e.target.value})}><option value="">{tt.choose}</option><option value="yes">{dt.yes}</option><option value="no">{dt.no}</option></select></label><label className="wide"><span>{t.open}</span><Input value={draft.openingHours} onChange={e=>setDraft({...draft,openingHours:e.target.value})} placeholder="bijv. 08:00–20:00"/></label><label className="wide"><span>{tt.note}</span><textarea value={draft.communityNote} onChange={e=>setDraft({...draft,communityNote:e.target.value})} rows={3}/></label></div>}{!reportSaved&&<DialogFooter><Button variant="outline" onClick={()=>setReportOpen(false)}>{t.cancel}</Button><Button onClick={saveReport}>{t.save}</Button></DialogFooter>}</DialogContent></Dialog>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="report-dialog"><DialogHeader><DialogTitle>{at.settings}</DialogTitle><DialogDescription>{at.settingsIntro}</DialogDescription></DialogHeader><div className="form-stack"><label><span>{at.profileName}</span><Input value={profileName} onChange={e=>setProfileName(e.target.value)}/></label><label><span>{at.phone}</span><Input inputMode="tel" value={contact} onChange={e=>setContact(e.target.value)} placeholder="+31 6 …"/></label></div><DialogFooter><Button variant="outline" onClick={()=>setSettingsOpen(false)}>{t.cancel}</Button><Button onClick={saveSettings}>{t.save}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={reminderOpen} onOpenChange={setReminderOpen}><DialogContent className="report-dialog"><DialogHeader><DialogTitle>{at.addReminder}</DialogTitle><DialogDescription>{at.demoPlan}</DialogDescription></DialogHeader><div className="form-stack"><label><span>{at.reminderTitle}</span><Input value={reminderTitle} onChange={e=>setReminderTitle(e.target.value)} placeholder={t.medication}/></label><label><span>{at.dateTime}</span><Input type="datetime-local" value={reminderAt} onChange={e=>setReminderAt(e.target.value)}/></label></div><DialogFooter><Button variant="outline" onClick={()=>setReminderOpen(false)}>{t.cancel}</Button><Button onClick={saveReminder} disabled={!reminderTitle.trim()||!reminderAt}>{t.save}</Button></DialogFooter></DialogContent></Dialog>
 </main>
}
