"use client";

import { useEffect, useRef } from "react";
import type { Map as LeafletMap, Marker } from "leaflet";

export type ToiletPlace = { id:string;name:string;lat:number;lon:number;wheelchair:string;fee:string;openingHours:string|null;changingTable:string;access:string;source:string;custom?:boolean;demo?:boolean;inferred?:boolean;googlePlaceId?:string|null;updatedAt?:string|null;operator?:string|null;website?:string|null;wheelchairDescription?:string|null;supervised?:string|null;centralKey?:string|null;paperSupplied?:string|null;handwashing?:string|null;hotWater?:string|null;position?:string|null;ostomy?:string|null;unisex?:string|null;drinkingWater?:string|null;rawSource?:string|null;communityNote?:string|null;verifiedAt?:string|null;baseSource?:string|null };

export function RealMap({ center, places, selectedId, onSelect }:{ center:{lat:number;lon:number}|null; places:ToiletPlace[]; selectedId:string|null; onSelect:(id:string)=>void }) {
  const elementRef=useRef<HTMLDivElement>(null); const mapRef=useRef<LeafletMap|null>(null); const markersRef=useRef<Marker[]>([]); const userMarkerRef=useRef<Marker|null>(null);
  useEffect(()=>{let cancelled=false; (async()=>{if(!elementRef.current||mapRef.current)return; const L=await import("leaflet"); if(cancelled||!elementRef.current)return; const c=center||{lat:51.72,lon:5.3}; const map=L.map(elementRef.current,{zoomControl:false}).setView([c.lat,c.lon],14); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a>'}).addTo(map); L.control.zoom({position:"bottomright"}).addTo(map); mapRef.current=map; setTimeout(()=>map.invalidateSize(),60)})(); return()=>{cancelled=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[]);
  useEffect(()=>{(async()=>{const L=await import("leaflet"); const map=mapRef.current;if(!map||!center)return;if(userMarkerRef.current)userMarkerRef.current.remove(); const icon=L.divIcon({className:"user-location-icon",html:"<span></span>",iconSize:[28,28],iconAnchor:[14,14]});userMarkerRef.current=L.marker([center.lat,center.lon],{icon}).addTo(map).bindTooltip("Jouw locatie");map.setView([center.lat,center.lon],14)})()},[center]);
  useEffect(()=>{(async()=>{const L=await import("leaflet");const map=mapRef.current;if(!map)return;markersRef.current.forEach(m=>m.remove());markersRef.current=places.map(place=>{const selected=place.id===selectedId;const icon=L.divIcon({className:"toilet-leaflet-icon",html:`<span class="${selected?"selected":""}">WC</span>`,iconSize:[42,42],iconAnchor:[21,38]});const marker=L.marker([place.lat,place.lon],{icon}).addTo(map).bindTooltip(place.name);marker.on("click",()=>onSelect(place.id));return marker});if(center){const chosen=places.find(place=>place.id===selectedId)||places[0];if(chosen){const bounds=L.latLngBounds([[center.lat,center.lon],[chosen.lat,chosen.lon]]);map.fitBounds(bounds,{padding:[55,55],maxZoom:16})}else{map.setView([center.lat,center.lon],15)}}})()},[places,selectedId,onSelect,center]);
  return <div ref={elementRef} className="real-map" aria-label="Kaart met toiletten"/>;
}
